- name: FTP Deploy
  uses: SamKirkland/FTP-Deploy-Action@4.1.0
  with:
    ftp-server: ${{ secrets.FTP_HOST }}
    ftp-username: ${{ secrets.FTP_USERNAME }}
    ftp-password: ${{ secrets.FTP_PASSWORD }}
    local-dir: ./
    server-dir: /public_html/
