steps:
  - name: Upload files via FTP
    uses: sebastianpopp/ftp-action@v1
    with:
      host: ${{ secrets.FTP_HOST }}
      user: ${{ secrets.FTP_USERNAME }}
      password: ${{ secrets.FTP_PASSWORD }}
      localDir: .  # Локальная директория для загрузки
      remoteDir: /public_html/  # Путь на сервере
