<?php
	include 'mnn.php'; // перевести на уровень выше!
	header('Content-Type: application/json');
	$link = firstconnect ();
	//enterregistration ();

	$current_datetime = new DateTime();
	$yesterday_datetime = (clone $current_datetime)->sub(new DateInterval('P1D'));

	$goods = ExecSQL($link,"SELECT * 
		FROM goods 
		LEFT JOIN goods_ftb ON goods.art_f = goods_ftb.good_art_ftb 
		WHERE datetime_update < NOW() - INTERVAL 1 DAY 
		   OR datetime_update IS NULL 
		   OR goods_ftb.good_art_ftb IS NULL 
		LIMIT 15;
		");
	
	foreach ($goods as $good)
	{
		
		$art 	= $good['art'];
		$art_f 	= $good['art_f'];
		
		$goods_ftb_record = ExecSQL($link,"SELECT * FROM goods_ftb WHERE good_art=$art;");
		if ($goods_ftb_record==NULL) 
			ExecSQL($link,"INSERT INTO goods_ftb (good_art,good_art_ftb) VALUES ($art,$art_f)");
		
		$goods_ftb_record1 = ExecSQL($link,"SELECT * FROM goods_ftb WHERE good_art=$art;")[0];
		$goods_ftb_id = $goods_ftb_record1['id'];
		$goods_ftb_datetime = $goods_ftb_record1['datetime_update'];
		
		if ($goods_ftb_datetime!=NULL) $goods_ftb_datetime = new DateTime($goods_ftb_datetime);
		
		if ($goods_ftb_record!=NULL AND $goods_ftb_datetime !=NULL AND $goods_ftb_datetime > $yesterday_datetime AND $goods_ftb_record1['price_ftb']>0) continue;
		
		if ($goods_ftb_record!=NULL)
			$site_ftb = file_get_contents($goods_ftb_record[0]['link_ftb']);
		
		if ($goods_ftb_record==NULL OR $site_ftb==NULL OR strlen($site_ftb)<100)
		{
			$url_for_search = 'https://fito.by/wp-admin/admin-ajax.php?action=flatsome_ajax_search_products&query='.$art_f;
			$res_search_string = file_get_contents($url_for_search);
			$res_search_string = preg_replace('/^\xEF\xBB\xBF/', '', $res_search_string);
			$res_search = json_decode($res_search_string, true);
			
			$leftstr = "https://fito.by/product/$art_f-";
			

			foreach ($res_search['suggestions'] as $res1)
			{
				if (substr($res1['url'], 0, strlen($leftstr)) === $leftstr) 
				{
					$link_ftb = $res1['url'];
					$site_ftb = file_get_contents($link_ftb);
					$que = "UPDATE goods_ftb SET datetime_update=CURRENT_TIMESTAMP(), link_ftb='$link_ftb' WHERE id=$goods_ftb_id";
					echo $que.PHP_EOL;
					ExecSQL($link,$que);
					break 1;
					
				}
			}
	
		}

			
			if (preg_match('/<meta name="twitter:description" content="([^"]*)"/i', $site_ftb, $matches)) 
				$good_def1 = str_replace("'","",$matches[1]);
				
			if (preg_match('/<img[^>]+src="([^"]+-600x600\.jpg)"[^>]*>/i', $site_ftb, $matches)) 
				$img = $matches[1]; 

			if (preg_match('/<span class="woocommerce-Price-amount amount">([0-9,.]+)&nbsp;<span class="woocommerce-Price-currencySymbol">/i', $site_ftb, $matches)) 
				$price = $matches[1];

			if (preg_match('/<span>Производитель:\s*([^<]+)<\/span>/i', $site_ftb, $matches)) 
				$producer = str_replace("'","",trim($matches[1])); 

			if (preg_match('/<nav class="woocommerce-breadcrumb breadcrumbs">.*?<a[^>]+href="[^"]*">([^<]+)<\/a>.*?<span class="divider">[^<]*<\/span>.*?<a[^>]+href="[^"]*">([^<]+)<\/a>/is', $site_ftb, $matches)) {
				$cat = trim($matches[1]);
				$subcat = trim($matches[2]);
			}
			
			echo "art = $art  art_f = $art_f    cat = $cat    subcat = $subcat".PHP_EOL;
			
			

			if (preg_match('/<div class="panel entry-content active"[^>]*>(.*?)<\/div>/is', $site_ftb, $matches)) {
				$good_def2 = $matches[1];
				$good_def2 = preg_replace('/<br\s*\/?>/i', "\n", $good_def2);
				$good_def2 = strip_tags($good_def2);
				$good_def2 = preg_replace("/\n+/", "\n", $good_def2);
				$good_def2 = trim($good_def2);
			}

			if (preg_match('/<h1[^>]*class="product-title product_title entry-title"[^>]*>([^<]+)<\/h1>/i', $site_ftb, $matches)) 
				$name = str_replace("'","",trim($matches[1]));

			$que = "UPDATE goods_ftb SET datetime_update=CURRENT_TIMESTAMP(), ftb_name='$name', img='$img', price_ftb='$price', producer='$producer', cat='$cat', subcat='$subcat', good_def1='$good_def1', good_def2='$good_def2' WHERE id=$goods_ftb_id";
			echo PHP_EOL.$que.PHP_EOL;
			ExecSQL($link,$que);


			$fullpath = "goods_pics/$art.png";

			$ch = curl_init($img);
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
			curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
			$imageData = curl_exec($ch);
			curl_close($ch);
			
			echo "fullpath=$fullpath".PHP_EOL;
			echo "img=$img".PHP_EOL;

			$image = imagecreatefromstring($imageData);
			if (!imagepng($image, $fullpath)) 
				die('Failed to save image as PNG.');
			
			
			
			

		
	}
	
	
	ExecSQL($link, "UPDATE goods g
JOIN goods_ftb f ON g.art = f.good_art
SET 
    g.art_f = f.good_art_ftb,
    g.name = f.ftb_name,
    g.description_short = f.good_def1,
    g.description_full = f.good_def2,
    g.pic_name = CONCAT(g.art, '.png'),
    g.price_old = f.price_ftb,
	g.cat = f.cat,
	g.subcat = f.subcat,
    g.producer = f.producer;");
		
		
	


		
	
